### ISSUE TITLE
Propuesta "Podrias agregar una seccion de Tecnologias"

### ISSUE THREAD

**Issue by AlexZerpa** [margarita264/FULLSTACK-MODULO1-Portafolio#5]
Hola Margarita, estaba viendo tu portfolio, seria bueno que incorpores una sección de tecnologías con las que trabajas. Esto te ayudara a mejorar tu Portfolio. Recuerda que cuando agregues una nueva sección, deberás cambiar los colores para que se vea como en el DISEÑO CSS 😊
Saludos 😎

**Comment by margarita264** [comment]
Gracias por el aporte
